# Generated by Django 3.2.7 on 2021-09-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='check_in_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
